import { describe, expect, it } from "vitest";
import fixtures from "@/eval/fixtures.json";
import { score, topContributions, type ScoringInput } from "./uplift";

/**
 * Proves the TypeScript scorer matches the Python trainer.
 *
 * The model is fitted in Python and scored in TypeScript, so the two
 * implementations of feature building, standardisation, the logistic and the
 * calibration must agree exactly. Fixtures are generated by eval/train.py from
 * held-out rows. If these drift apart, every downstream rupee is wrong and
 * nothing else in the system would notice — so this is the test that stops it.
 */

type Fixture = {
  input: {
    amount_paise: number;
    risk_class: string;
    taxonomy_class: string | null;
    method: string | null;
    hours_since_event: number;
    hour: number;
    weekday: number;
    days_to_payday: number;
    downtime_active: number;
    cust_success_count: number;
    cust_failure_count: number;
    cust_tenure_days: number;
    ltv_band: number;
    prior_contacts_7d: number;
  };
  p_control: number;
  p_contact: number;
  uplift: number;
};

function toInput(f: Fixture["input"]): ScoringInput {
  return {
    amountPaise: f.amount_paise,
    riskClass: f.risk_class,
    taxonomyClass: f.taxonomy_class,
    method: f.method,
    hoursSinceEvent: f.hours_since_event,
    hour: f.hour,
    weekday: f.weekday,
    daysToPayday: f.days_to_payday,
    downtimeActive: Boolean(f.downtime_active),
    custSuccessCount: f.cust_success_count,
    custFailureCount: f.cust_failure_count,
    custTenureDays: f.cust_tenure_days,
    ltvBand: f.ltv_band,
    priorContacts7d: f.prior_contacts_7d,
  };
}

describe("uplift scorer parity with Python", () => {
  const cases = fixtures as unknown as Fixture[];

  it("has fixtures to check against", () => {
    expect(cases.length).toBeGreaterThan(10);
  });

  it("matches Python to 6 decimal places on every fixture", () => {
    for (const f of cases) {
      const s = score(toInput(f.input));
      expect(s.pControl).toBeCloseTo(f.p_control, 6);
      expect(s.pContact).toBeCloseTo(f.p_contact, 6);
      expect(s.uplift).toBeCloseTo(f.uplift, 6);
    }
  });

  it("produces probabilities inside [0, 1]", () => {
    for (const f of cases) {
      const s = score(toInput(f.input));
      expect(s.pControl).toBeGreaterThanOrEqual(0);
      expect(s.pControl).toBeLessThanOrEqual(1);
      expect(s.pContact).toBeGreaterThanOrEqual(0);
      expect(s.pContact).toBeLessThanOrEqual(1);
    }
  });

  it("exposes contributions that explain the score", () => {
    const s = score(toInput(cases[0].input));
    const top = topContributions(s.contributions, 5);
    expect(top.length).toBeGreaterThan(0);
    expect(top[0][0]).toBeTruthy();
    // Sorted by absolute magnitude.
    for (let i = 1; i < top.length; i++) {
      expect(Math.abs(top[i - 1][1])).toBeGreaterThanOrEqual(Math.abs(top[i][1]));
    }
  });

  it("scores an unknown categorical level without throwing", () => {
    // Robustness: a new Razorpay error_reason must degrade, not crash.
    const s = score({ ...toInput(cases[0].input), method: "cryptocurrency", taxonomyClass: "NEW" });
    expect(Number.isFinite(s.uplift)).toBe(true);
  });
});
