import model from "@/eval/model.json";

/**
 * Uplift scoring in TypeScript, from the artefact trained by eval/train.py.
 *
 * There is no Python service. Logistic scoring is a dot product, a sigmoid and
 * a two-parameter calibration, so shipping the coefficients removes an entire
 * runtime, deployment target and network hop from the production path
 * (DECISIONS.md §4).
 *
 * The correctness risk this creates is drift between the two implementations,
 * so `buildFeatures` below must stay identical to `build_features` in
 * eval/train.py. lib/uplift.test.ts proves it against fixtures generated by the
 * Python side — if the two ever disagree, the tests fail rather than the money
 * being quietly wrong.
 */

export interface ScoringInput {
  amountPaise: number;
  riskClass: string;
  taxonomyClass: string | null;
  method: string | null;
  hoursSinceEvent: number;
  hour: number;
  weekday: number;
  daysToPayday: number;
  downtimeActive: boolean;
  custSuccessCount: number;
  custFailureCount: number;
  custTenureDays: number;
  ltvBand: number;
  priorContacts7d: number;
}

export interface UpliftScore {
  pControl: number;
  pContact: number;
  /** The number everything downstream ranks on. */
  uplift: number;
  modelVersion: string;
  /** Signed feature contributions to the contact arm, for the audit trail. */
  contributions: Record<string, number>;
}

const EPS = 1e-6;

/** Mirrors build_features() in eval/train.py. Order matters. */
export function buildFeatures(x: ScoringInput): number[] {
  const numeric: Record<string, number> = {
    log_amount: Math.log1p(x.amountPaise),
    hours_since_event: x.hoursSinceEvent,
    hour: x.hour,
    weekday: x.weekday,
    days_to_payday: x.daysToPayday,
    downtime_active: x.downtimeActive ? 1 : 0,
    cust_success_count: x.custSuccessCount,
    cust_failure_count: x.custFailureCount,
    log_tenure: Math.log1p(x.custTenureDays),
    ltv_band: x.ltvBand,
    prior_contacts_7d: x.priorContacts7d,
  };

  const out = model.numeric.map((n) => numeric[n]);

  const categoricalValue: Record<string, string> = {
    risk_class: x.riskClass,
    taxonomy_class: x.taxonomyClass ?? "",
    method: x.method ?? "",
  };

  for (const [field, levels] of Object.entries(model.categorical)) {
    for (const lv of levels as string[]) {
      out.push(categoricalValue[field] === lv ? 1 : 0);
    }
  }
  return out;
}

function standardise(raw: number[]): number[] {
  const { mean, scale } = model.scaler;
  return raw.map((v, i) => (v - mean[i]) / scale[i]);
}

function sigmoid(z: number): number {
  return 1 / (1 + Math.exp(-z));
}

/** Platt scaling, as fitted in eval/train.py. */
function calibrate(raw: number, a: number, b: number): number {
  const p = Math.min(Math.max(raw, EPS), 1 - EPS);
  return sigmoid(a * Math.log(p / (1 - p)) + b);
}

type Arm = {
  intercept: number;
  coef: number[];
  calibration: { kind: string; a: number; b: number };
};

function scoreArm(z: number[], arm: Arm): number {
  let logit = arm.intercept;
  for (let i = 0; i < z.length; i++) logit += z[i] * arm.coef[i];
  return calibrate(sigmoid(logit), arm.calibration.a, arm.calibration.b);
}

export function score(input: ScoringInput): UpliftScore {
  const z = standardise(buildFeatures(input));
  const arms = model.arms as unknown as { control: Arm; contact: Arm };

  const pControl = scoreArm(z, arms.control);
  const pContact = scoreArm(z, arms.contact);

  // Contribution of each feature to the contact-arm logit. Turns "recovery
  // probability 0.81" into something a merchant can argue with.
  const contributions: Record<string, number> = {};
  for (let i = 0; i < z.length; i++) {
    const c = z[i] * arms.contact.coef[i];
    if (Math.abs(c) > 1e-9) contributions[model.feature_names[i]] = Number(c.toFixed(4));
  }

  return {
    pControl,
    pContact,
    uplift: pContact - pControl,
    modelVersion: model.version,
    contributions,
  };
}

/** The largest movers, for the decision drilldown. */
export function topContributions(
  contributions: Record<string, number>,
  n = 5,
): Array<[string, number]> {
  return Object.entries(contributions)
    .sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))
    .slice(0, n);
}

export const MODEL_VERSION = model.version;
